// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd_Ah9rg53bEtcVyuLPYtEXM7VAiU00ug',
    appId: '1:560111841252:web:6f95b1ddee9f6422c8e1f1',
    messagingSenderId: '560111841252',
    projectId: 'cashease-d6816',
    authDomain: 'cashease-d6816.firebaseapp.com',
    storageBucket: 'cashease-d6816.firebasestorage.app',
    measurementId: 'G-DR5Q18G2JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdR99ctaGC6uxfaGgsLvULTPIfMuKnmw0',
    appId: '1:560111841252:android:b456ff9dec8b0318c8e1f1',
    messagingSenderId: '560111841252',
    projectId: 'cashease-d6816',
    storageBucket: 'cashease-d6816.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMMH2LrmO1ACEFXNxvjkNUMzXKMtWR2HI',
    appId: '1:560111841252:ios:fe66b77791acdfa5c8e1f1',
    messagingSenderId: '560111841252',
    projectId: 'cashease-d6816',
    storageBucket: 'cashease-d6816.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMMH2LrmO1ACEFXNxvjkNUMzXKMtWR2HI',
    appId: '1:560111841252:ios:fe66b77791acdfa5c8e1f1',
    messagingSenderId: '560111841252',
    projectId: 'cashease-d6816',
    storageBucket: 'cashease-d6816.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd_Ah9rg53bEtcVyuLPYtEXM7VAiU00ug',
    appId: '1:560111841252:web:900b99f2647d9f80c8e1f1',
    messagingSenderId: '560111841252',
    projectId: 'cashease-d6816',
    authDomain: 'cashease-d6816.firebaseapp.com',
    storageBucket: 'cashease-d6816.firebasestorage.app',
    measurementId: 'G-601XHCBNQ8',
  );
}
